export type Catalog77393Item = {
  id: string;
  number: number;
  name: { id: string; en: string };
  category: string;
  summary: { id: string; en: string };
  useCases: string[];
  rental: string;
  priority: "top" | "easy" | "standard" | "specialist";
  imageKey: string;
  tags: string[];
};

export const catalog77393 = [
  {
    id: "truck-mounted-crane",
    number: 38,
    name: { id: "Truck Mounted Crane", en: "Truck-Mounted Crane" },
    category: "crane-lifting",
    summary: {
      id: "Truk serbaguna untuk mengangkut sekaligus mengangkat mesin, material, dan peralatan proyek.",
      en: "A versatile truck for transporting and lifting machinery, materials, and project equipment.",
    },
    useCases: ["machine installation", "steel handling", "generator delivery"],
    rental: "Per shift / harian",
    priority: "easy",
    imageKey: "truck-mounted-crane",
    tags: ["crane", "truck", "lifting", "self-loading"],
  },
  {
    id: "knuckle-boom-crane",
    number: 39,
    name: { id: "Knuckle Boom Crane", en: "Knuckle Boom Crane" },
    category: "crane-lifting",
    summary: {
      id: "Crane lipat yang ringkas untuk bongkar muat mandiri di area kerja dengan ruang terbatas.",
      en: "A compact folding crane for self-loading operations in space-constrained work areas.",
    },
    useCases: ["pipe handling", "material delivery", "urban construction"],
    rental: "Harian / per proyek",
    priority: "easy",
    imageKey: "knuckle-boom-crane",
    tags: ["crane", "articulated-boom", "self-loading", "materials"],
  },
  {
    id: "mobile-crane-10-25t",
    number: 40,
    name: { id: "Mobile Crane 10–25 Ton", en: "10–25 Ton Mobile Crane" },
    category: "crane-lifting",
    summary: {
      id: "Mobile crane kelas ringan untuk pekerjaan lifting umum dan instalasi konstruksi.",
      en: "A light-class mobile crane for general lifting and construction installation work.",
    },
    useCases: ["general lifting", "equipment placement", "structural installation"],
    rental: "8 jam / harian",
    priority: "top",
    imageKey: "mobile-crane-10-25t",
    tags: ["mobile-crane", "10-25t", "lifting", "construction"],
  },
  {
    id: "mobile-crane-35-50t",
    number: 41,
    name: { id: "Mobile Crane 35–50 Ton", en: "35–50 Ton Mobile Crane" },
    category: "crane-lifting",
    summary: {
      id: "Mobile crane kapasitas menengah untuk instalasi struktur dan pekerjaan plant.",
      en: "A medium-capacity mobile crane for structural installation and plant work.",
    },
    useCases: ["plant maintenance", "steel erection", "machinery lifting"],
    rental: "Per shift / harian / bulanan",
    priority: "easy",
    imageKey: "mobile-crane-35-50t",
    tags: ["mobile-crane", "35-50t", "plant", "construction"],
  },
  {
    id: "mobile-crane-80-100t",
    number: 42,
    name: { id: "Mobile Crane 80–100 Ton", en: "80–100 Ton Mobile Crane" },
    category: "crane-lifting",
    summary: {
      id: "Mobile crane heavy-duty untuk pengangkatan mesin dan komponen proyek berkapasitas besar.",
      en: "A heavy-duty mobile crane for lifting large machinery and project components.",
    },
    useCases: ["heavy machinery", "EPC projects", "large structural components"],
    rental: "Harian / per proyek",
    priority: "standard",
    imageKey: "mobile-crane-80-100t",
    tags: ["mobile-crane", "80-100t", "heavy-lifting", "EPC"],
  },
  {
    id: "all-terrain-crane",
    number: 43,
    name: { id: "All Terrain Crane", en: "All-Terrain Crane" },
    category: "crane-lifting",
    summary: {
      id: "Crane berkapasitas besar dengan mobilitas jalan raya dan kemampuan menjangkau medan proyek.",
      en: "A high-capacity crane combining road mobility with access to demanding project terrain.",
    },
    useCases: ["refinery projects", "power plants", "large infrastructure"],
    rental: "Per proyek",
    priority: "specialist",
    imageKey: "all-terrain-crane",
    tags: ["all-terrain", "heavy-lifting", "refinery", "infrastructure"],
  },
  {
    id: "rough-terrain-crane",
    number: 44,
    name: { id: "Rough Terrain Crane", en: "Rough-Terrain Crane" },
    category: "crane-lifting",
    summary: {
      id: "Crane bermanuver tinggi untuk lifting di permukaan proyek yang kasar atau belum dipadatkan.",
      en: "A highly maneuverable crane for lifting on rough or unprepared project surfaces.",
    },
    useCases: ["civil sites", "remote projects", "industrial construction"],
    rental: "Harian / bulanan",
    priority: "standard",
    imageKey: "rough-terrain-crane",
    tags: ["rough-terrain", "crane", "off-road", "site-work"],
  },
  {
    id: "crawler-crane",
    number: 45,
    name: { id: "Crawler Crane", en: "Crawler Crane" },
    category: "crane-lifting",
    summary: {
      id: "Crane berantai yang stabil untuk erection struktur berat dan proyek jangka panjang.",
      en: "A stable crawler-mounted crane for heavy structural erection and long-duration projects.",
    },
    useCases: ["heavy structures", "bridge construction", "EPC projects"],
    rental: "Bulanan / per proyek",
    priority: "specialist",
    imageKey: "crawler-crane",
    tags: ["crawler", "crane", "heavy-structure", "long-term"],
  },
  {
    id: "tower-crane",
    number: 46,
    name: { id: "Tower Crane", en: "Tower Crane" },
    category: "crane-lifting",
    summary: {
      id: "Crane vertikal untuk memindahkan material pada konstruksi gedung bertingkat.",
      en: "A vertical crane for moving materials across high-rise construction sites.",
    },
    useCases: ["high-rise buildings", "vertical material handling", "urban development"],
    rental: "Bulanan / per proyek",
    priority: "standard",
    imageKey: "tower-crane",
    tags: ["tower-crane", "high-rise", "building", "vertical-lifting"],
  },
  {
    id: "gantry-crane",
    number: 47,
    name: { id: "Gantry Crane", en: "Gantry Crane" },
    category: "crane-lifting",
    summary: {
      id: "Sistem crane portal untuk pengangkatan berulang di fasilitas industri dan area fabrikasi.",
      en: "A portal crane system for repeat lifting in industrial facilities and fabrication areas.",
    },
    useCases: ["precast yards", "industrial fabrication", "heavy assembly"],
    rental: "Per proyek",
    priority: "specialist",
    imageKey: "gantry-crane",
    tags: ["gantry", "stationary-crane", "industrial", "fabrication"],
  },
  {
    id: "man-basket-personnel-lift",
    number: 48,
    name: { id: "Man Basket / Personnel Lift", en: "Man Basket / Personnel Lift" },
    category: "access-equipment",
    summary: {
      id: "Platform akses untuk membantu personel mencapai titik kerja di ketinggian.",
      en: "An access platform designed to help personnel reach elevated work points.",
    },
    useCases: ["facade work", "inspection", "installation at height"],
    rental: "Harian / bulanan",
    priority: "easy",
    imageKey: "man-basket-personnel-lift",
    tags: ["personnel-lift", "work-at-height", "access", "maintenance"],
  },
  {
    id: "mini-excavator",
    number: 49,
    name: { id: "Mini Excavator", en: "Mini Excavator" },
    category: "earthmoving",
    summary: {
      id: "Excavator ringkas untuk penggalian presisi di area sempit dan proyek utilitas.",
      en: "A compact excavator for precise digging in confined areas and utility projects.",
    },
    useCases: ["utility trenches", "drainage", "landscaping"],
    rental: "Harian / bulanan",
    priority: "easy",
    imageKey: "mini-excavator",
    tags: ["excavator", "compact", "utility", "drainage"],
  },
  {
    id: "excavator-10-15t",
    number: 50,
    name: { id: "Excavator 10–15 Ton", en: "10–15 Ton Excavator" },
    category: "earthmoving",
    summary: {
      id: "Excavator kelas menengah-ringan untuk pekerjaan galian dan pemuatan konstruksi umum.",
      en: "A light-medium excavator for general construction digging and loading.",
    },
    useCases: ["general excavation", "site preparation", "utility work"],
    rental: "Hour meter / bulanan",
    priority: "easy",
    imageKey: "excavator-10-15t",
    tags: ["excavator", "10-15t", "earthmoving", "construction"],
  },
  {
    id: "excavator-20t",
    number: 51,
    name: { id: "Excavator 20 Ton / Kelas PC200", en: "20 Ton / PC200-Class Excavator" },
    category: "earthmoving",
    summary: {
      id: "Excavator serbaguna untuk siklus gali, angkat, dan muat pada pekerjaan sipil.",
      en: "A versatile excavator for digging, lifting, and loading cycles in civil works.",
    },
    useCases: ["civil earthworks", "bulk excavation", "truck loading"],
    rental: "Hour meter / bulanan",
    priority: "top",
    imageKey: "excavator-20t",
    tags: ["excavator", "20t", "PC200-class", "earthmoving"],
  },
  {
    id: "excavator-30t",
    number: 52,
    name: { id: "Excavator 30 Ton / Kelas PC300", en: "30 Ton / PC300-Class Excavator" },
    category: "earthmoving",
    summary: {
      id: "Excavator kelas berat untuk volume earthmoving besar dan kondisi kerja yang menuntut.",
      en: "A heavy-class excavator for high-volume earthmoving and demanding work conditions.",
    },
    useCases: ["mass excavation", "infrastructure", "quarry support"],
    rental: "Hour meter / bulanan",
    priority: "top",
    imageKey: "excavator-30t",
    tags: ["excavator", "30t", "PC300-class", "heavy-earthmoving"],
  },
  {
    id: "excavator-40-50t",
    number: 53,
    name: { id: "Excavator 40–50 Ton", en: "40–50 Ton Excavator" },
    category: "earthmoving",
    summary: {
      id: "Excavator heavy-duty untuk penggalian volume besar dan pekerjaan material keras.",
      en: "A heavy-duty excavator for high-volume digging and challenging material conditions.",
    },
    useCases: ["heavy excavation", "quarrying", "large infrastructure"],
    rental: "Hour meter / bulanan",
    priority: "standard",
    imageKey: "excavator-40-50t",
    tags: ["excavator", "40-50t", "heavy-duty", "quarry"],
  },
  {
    id: "long-arm-excavator",
    number: 54,
    name: { id: "Long Arm Excavator", en: "Long-Reach Excavator" },
    category: "specialized-earthmoving",
    summary: {
      id: "Excavator berlengan panjang untuk penggalian pada titik yang sulit dijangkau dari darat.",
      en: "A long-reach excavator for digging points that are difficult to access from land.",
    },
    useCases: ["river normalization", "deep excavation", "dredging support"],
    rental: "Hour meter / per proyek",
    priority: "standard",
    imageKey: "long-arm-excavator",
    tags: ["excavator", "long-reach", "river", "dredging"],
  },
  {
    id: "amphibious-excavator",
    number: 55,
    name: { id: "Amphibious Excavator", en: "Amphibious Excavator" },
    category: "specialized-earthmoving",
    summary: {
      id: "Excavator dengan undercarriage ponton untuk pekerjaan rawa dan perairan dangkal.",
      en: "An excavator with a pontoon undercarriage for wetlands and shallow-water works.",
    },
    useCases: ["wetland construction", "swamp access", "shallow dredging"],
    rental: "Bulanan / per proyek",
    priority: "specialist",
    imageKey: "amphibious-excavator",
    tags: ["excavator", "amphibious", "wetland", "dredging"],
  },
  {
    id: "excavator-breaker",
    number: 56,
    name: { id: "Excavator dengan Breaker", en: "Excavator with Hydraulic Breaker" },
    category: "demolition",
    summary: {
      id: "Excavator berattachment breaker untuk memecah beton, batu, dan lapisan keras.",
      en: "An excavator fitted with a hydraulic breaker for concrete, rock, and hard layers.",
    },
    useCases: ["concrete demolition", "rock breaking", "foundation removal"],
    rental: "Hour meter / bulanan",
    priority: "top",
    imageKey: "excavator-breaker",
    tags: ["excavator", "breaker", "demolition", "rock"],
  },
  {
    id: "backhoe-loader",
    number: 57,
    name: { id: "Backhoe Loader", en: "Backhoe Loader" },
    category: "earthmoving",
    summary: {
      id: "Mesin dua fungsi untuk menggali dan memuat material pada pekerjaan sipil skala ringan.",
      en: "A dual-purpose machine for digging and loading in light civil works.",
    },
    useCases: ["utility work", "small excavation", "material loading"],
    rental: "Harian / bulanan",
    priority: "easy",
    imageKey: "backhoe-loader",
    tags: ["backhoe", "loader", "utility", "multi-purpose"],
  },
  {
    id: "wheel-loader",
    number: 58,
    name: { id: "Wheel Loader", en: "Wheel Loader" },
    category: "earthmoving",
    summary: {
      id: "Loader beroda untuk memindahkan material curah dan mengisi dump truck secara efisien.",
      en: "A wheeled loader for moving bulk materials and efficiently loading dump trucks.",
    },
    useCases: ["stockpile handling", "aggregate loading", "site material movement"],
    rental: "Hour meter / bulanan",
    priority: "top",
    imageKey: "wheel-loader",
    tags: ["wheel-loader", "loading", "stockpile", "aggregate"],
  },
  {
    id: "skid-steer-loader",
    number: 59,
    name: { id: "Skid Steer Loader", en: "Skid-Steer Loader" },
    category: "compact-equipment",
    summary: {
      id: "Loader kompak dan lincah untuk pemindahan material di ruang kerja terbatas.",
      en: "A compact, agile loader for moving materials in confined workspaces.",
    },
    useCases: ["site cleanup", "landscaping", "confined material handling"],
    rental: "Harian / bulanan",
    priority: "easy",
    imageKey: "skid-steer-loader",
    tags: ["skid-steer", "compact", "loader", "site-cleanup"],
  },
  {
    id: "bulldozer",
    number: 60,
    name: { id: "Bulldozer", en: "Bulldozer" },
    category: "earthmoving",
    summary: {
      id: "Alat berantai untuk mendorong material, merintis lahan, dan melakukan ripping.",
      en: "A tracked machine for pushing material, clearing land, and ripping hard ground.",
    },
    useCases: ["land clearing", "bulk pushing", "site preparation"],
    rental: "Hour meter / bulanan",
    priority: "top",
    imageKey: "bulldozer",
    tags: ["bulldozer", "dozer", "land-clearing", "earthmoving"],
  },
  {
    id: "motor-grader",
    number: 61,
    name: { id: "Motor Grader", en: "Motor Grader" },
    category: "road-construction",
    summary: {
      id: "Mesin grading untuk membentuk elevasi, kemiringan, dan permukaan jalan secara presisi.",
      en: "A grading machine for shaping road elevation, slope, and surface with precision.",
    },
    useCases: ["road formation", "subgrade finishing", "access-road maintenance"],
    rental: "Hour meter / bulanan",
    priority: "top",
    imageKey: "motor-grader",
    tags: ["motor-grader", "roadwork", "leveling", "civil"],
  },
  {
    id: "vibro-roller",
    number: 62,
    name: { id: "Vibro Roller", en: "Vibratory Roller" },
    category: "compaction",
    summary: {
      id: "Roller bergetar untuk memadatkan tanah dan lapisan agregat pada pekerjaan jalan.",
      en: "A vibratory roller for compacting soil and aggregate layers in roadworks.",
    },
    useCases: ["soil compaction", "road base", "embankments"],
    rental: "Harian / bulanan",
    priority: "easy",
    imageKey: "vibro-roller",
    tags: ["roller", "vibratory", "compaction", "roadwork"],
  },
  {
    id: "sheep-foot-roller",
    number: 63,
    name: { id: "Sheep Foot Roller", en: "Sheepsfoot Roller" },
    category: "compaction",
    summary: {
      id: "Roller berkaki padat untuk memadatkan tanah kohesif pada pekerjaan timbunan.",
      en: "A padfoot roller for compacting cohesive soil in embankment work.",
    },
    useCases: ["clay compaction", "embankments", "earth dams"],
    rental: "Harian / bulanan",
    priority: "easy",
    imageKey: "sheep-foot-roller",
    tags: ["roller", "padfoot", "soil-compaction", "earthwork"],
  },
  {
    id: "asphalt-paver",
    number: 64,
    name: { id: "Asphalt Paver", en: "Asphalt Paver" },
    category: "road-construction",
    summary: {
      id: "Mesin penghampar aspal untuk membentuk lapisan permukaan jalan yang konsisten.",
      en: "An asphalt-laying machine for producing a consistent road surface layer.",
    },
    useCases: ["highway paving", "urban roads", "parking areas"],
    rental: "Harian / per proyek",
    priority: "standard",
    imageKey: "asphalt-paver",
    tags: ["paver", "asphalt", "roadwork", "paving"],
  },
  {
    id: "cold-milling-machine",
    number: 65,
    name: { id: "Cold Milling Machine", en: "Cold Milling Machine" },
    category: "road-construction",
    summary: {
      id: "Mesin untuk mengupas lapisan aspal lama secara terukur sebelum rehabilitasi jalan.",
      en: "A machine for precisely removing old asphalt before road rehabilitation.",
    },
    useCases: ["road rehabilitation", "surface removal", "pavement repair"],
    rental: "Per proyek",
    priority: "standard",
    imageKey: "cold-milling-machine",
    tags: ["milling", "asphalt", "rehabilitation", "roadwork"],
  },
  {
    id: "concrete-mixer-truck",
    number: 66,
    name: { id: "Concrete Mixer Truck", en: "Concrete Mixer Truck" },
    category: "concrete-equipment",
    summary: {
      id: "Truk mixer untuk menjaga beton tetap homogen selama pengiriman ke area pengecoran.",
      en: "A mixer truck that keeps concrete homogeneous while in transit to the pour site.",
    },
    useCases: ["ready-mix delivery", "building construction", "civil structures"],
    rental: "Per trip / bulanan",
    priority: "easy",
    imageKey: "concrete-mixer-truck",
    tags: ["concrete", "mixer-truck", "ready-mix", "construction"],
  },
  {
    id: "concrete-pump-truck",
    number: 67,
    name: { id: "Concrete Pump Truck", en: "Concrete Pump Truck" },
    category: "concrete-equipment",
    summary: {
      id: "Truk pompa dengan boom untuk menyalurkan beton ke titik pengecoran yang sulit dijangkau.",
      en: "A boom-equipped pump truck for delivering concrete to hard-to-reach pour points.",
    },
    useCases: ["high-rise pours", "foundation work", "bridge construction"],
    rental: "Harian / per proyek",
    priority: "standard",
    imageKey: "concrete-pump-truck",
    tags: ["concrete", "pump-truck", "boom", "casting"],
  },
  {
    id: "mobile-batching-plant",
    number: 68,
    name: { id: "Mobile Batching Plant", en: "Mobile Batching Plant" },
    category: "concrete-equipment",
    summary: {
      id: "Fasilitas produksi beton modular yang dapat ditempatkan dekat area proyek berskala besar.",
      en: "A modular concrete production facility deployable near large-scale project sites.",
    },
    useCases: ["large infrastructure", "remote projects", "high-volume concrete"],
    rental: "Per proyek",
    priority: "specialist",
    imageKey: "mobile-batching-plant",
    tags: ["batching-plant", "concrete", "mobile", "infrastructure"],
  },
] satisfies Catalog77393Item[];
