export const catalog77100 = [
  {
    id: "pickup-light-truck",
    number: 1,
    name: { id: "Pickup / Light Truck", en: "Pickup / Light Truck" },
    category: "Light Commercial Vehicle",
    summary: {
      id: "Solusi angkut ringan untuk spare part, peralatan, dan kebutuhan operasional harian.",
      en: "A light-duty transport solution for spare parts, tools, and daily operations.",
    },
    useCases: ["Warehouse", "Site tambang", "Konstruksi", "Distribusi ringan"],
    rental: "Harian / bulanan / per trip",
    priority: "easy",
    imageKey: "pickup-light-truck",
    tags: ["pickup", "light-truck", "cargo", "site-vehicle"],
  },
  {
    id: "cde-engkel-box",
    number: 2,
    name: { id: "CDE / Engkel Box", en: "CDE / Light Box Truck" },
    category: "Box Truck",
    summary: {
      id: "Truk box ringkas untuk distribusi barang skala kecil hingga menengah.",
      en: "A compact box truck for small-to-medium distribution requirements.",
    },
    useCases: ["FMCG", "Warehouse", "Corporate distribution", "Last-mile logistics"],
    rental: "Per trip / dedicated bulanan",
    priority: "easy",
    imageKey: "cde-engkel-box",
    tags: ["cde", "engkel", "box-truck", "distribution"],
  },
  {
    id: "cdd-box",
    number: 3,
    name: { id: "CDD Box", en: "CDD Box Truck" },
    category: "Box Truck",
    summary: {
      id: "Truk box enam roda untuk kebutuhan distribusi kelas menengah sesuai konfigurasi muatan.",
      en: "A six-wheel box truck for medium-duty distribution, subject to payload configuration.",
    },
    useCases: ["Retail", "Industrial", "Logistics", "Regional distribution"],
    rental: "Per trip / bulanan",
    priority: "easy",
    imageKey: "cdd-box",
    tags: ["cdd", "six-wheel", "box-truck", "logistics"],
  },
  {
    id: "cdd-long",
    number: 4,
    name: { id: "CDD Long", en: "CDD Long Box Truck" },
    category: "Box Truck",
    summary: {
      id: "Konfigurasi box panjang untuk kargo bervolume besar dengan bobot moderat.",
      en: "A long-box configuration for high-volume cargo with moderate weight.",
    },
    useCases: ["Logistics regional", "Retail distribution", "Volumetric cargo"],
    rental: "Per trip / dedicated",
    priority: "easy",
    imageKey: "cdd-long",
    tags: ["cdd-long", "long-box", "volume-cargo", "regional-logistics"],
  },
  {
    id: "fuso-box",
    number: 5,
    name: { id: "Fuso Box", en: "Fuso Box Truck" },
    category: "Heavy Box Truck",
    summary: {
      id: "Truk box medium-heavy untuk distribusi regional dan muatan besar sesuai spesifikasi unit.",
      en: "A medium-heavy box truck for regional distribution and larger loads, subject to unit specifications.",
    },
    useCases: ["Regional distribution", "Industrial cargo", "Warehouse transfer"],
    rental: "Per trip / bulanan",
    priority: "easy",
    imageKey: "fuso-box",
    tags: ["fuso", "heavy-box", "regional", "cargo"],
  },
  {
    id: "wingbox",
    number: 6,
    name: { id: "Wingbox", en: "Wingbox Truck" },
    category: "Specialized Box Truck",
    summary: {
      id: "Box bersisi buka untuk mempercepat bongkar-muat pallet dari sisi kendaraan.",
      en: "A side-opening box truck designed for faster lateral pallet loading and unloading.",
    },
    useCases: ["FMCG", "Manufacturing", "3PL", "Factory-to-DC"],
    rental: "Per trip / dedicated bulanan",
    priority: "top",
    imageKey: "wingbox",
    tags: ["wingbox", "pallet", "fmcg", "dedicated-fleet"],
  },
  {
    id: "tronton-box",
    number: 7,
    name: { id: "Tronton Box", en: "Tronton Box Truck" },
    category: "Heavy Box Truck",
    summary: {
      id: "Truk box tiga axle untuk kebutuhan logistik antarkota dengan volume dan tonase lebih besar.",
      en: "A three-axle box truck for intercity logistics requiring greater volume and payload.",
    },
    useCases: ["Intercity logistics", "High-volume distribution", "Industrial cargo"],
    rental: "Per trip / kontrak",
    priority: "easy",
    imageKey: "tronton-box",
    tags: ["tronton", "three-axle", "box-truck", "intercity"],
  },
  {
    id: "tronton-wingbox",
    number: 8,
    name: { id: "Tronton Wingbox", en: "Tronton Wingbox Truck" },
    category: "Specialized Box Truck",
    summary: {
      id: "Wingbox berkapasitas besar untuk distribusi massal pallet dan kargo antarfasilitas.",
      en: "A high-capacity wingbox for mass pallet and cargo distribution between facilities.",
    },
    useCases: ["Factory-to-DC", "Manufacturing", "3PL", "Mass distribution"],
    rental: "Dedicated / bulanan",
    priority: "top",
    imageKey: "tronton-wingbox",
    tags: ["tronton", "wingbox", "factory-to-dc", "pallet"],
  },
  {
    id: "curtain-sider",
    number: 9,
    name: { id: "Curtain Sider", en: "Curtain-Side Truck" },
    category: "Specialized Box Truck",
    summary: {
      id: "Kendaraan bertirai samping sebagai alternatif fleksibel untuk pengangkutan kargo pallet.",
      en: "A curtain-side vehicle offering flexible access for palletized cargo transport.",
    },
    useCases: ["Manufacturing", "Pallet cargo", "Industrial distribution"],
    rental: "Per trip / bulanan",
    priority: "easy",
    imageKey: "curtain-sider",
    tags: ["curtain-sider", "pallet", "side-loading", "manufacturing"],
  },
  {
    id: "flatbed-truck",
    number: 10,
    name: { id: "Flatbed Truck", en: "Flatbed Truck" },
    category: "Project Transportation",
    summary: {
      id: "Truk deck terbuka untuk baja, pipa, mesin, dan material berdimensi khusus.",
      en: "An open-deck truck for steel, pipes, machinery, and oversized materials.",
    },
    useCases: ["Konstruksi", "Pertambangan", "Oil and gas", "Project cargo"],
    rental: "Per trip / harian / bulanan",
    priority: "easy",
    imageKey: "flatbed-truck",
    tags: ["flatbed", "open-deck", "oversized-cargo", "project-logistics"],
  },
  {
    id: "prime-mover",
    number: 11,
    name: { id: "Prime Mover", en: "Prime Mover" },
    category: "Tractor & Trailer",
    summary: {
      id: "Kepala traktor untuk menarik container chassis dan beragam konfigurasi trailer.",
      en: "A tractor head for hauling container chassis and multiple trailer configurations.",
    },
    useCases: ["Pelabuhan", "Pertambangan", "Logistics", "Trailer hauling"],
    rental: "Per trip / bulanan",
    priority: "top",
    imageKey: "prime-mover",
    tags: ["prime-mover", "tractor-head", "trailer", "container"],
  },
  {
    id: "container-trailer-20ft",
    number: 12,
    name: { id: "Trailer Container 20 ft", en: "20-ft Container Trailer" },
    category: "Container Transportation",
    summary: {
      id: "Kombinasi prime mover dan chassis untuk mobilisasi container 20 kaki.",
      en: "A prime mover and chassis combination for 20-foot container transport.",
    },
    useCases: ["Port-to-warehouse", "Container depot", "Import-export logistics"],
    rental: "Per trip",
    priority: "easy",
    imageKey: "container-trailer-20ft",
    tags: ["20ft-container", "chassis", "port-logistics", "trailer"],
  },
  {
    id: "container-trailer-40ft",
    number: 13,
    name: { id: "Trailer Container 40 ft", en: "40-ft Container Trailer" },
    category: "Container Transportation",
    summary: {
      id: "Chassis panjang untuk kebutuhan pengangkutan container 40 kaki dalam jaringan logistik.",
      en: "A long chassis for transporting 40-foot containers across logistics networks.",
    },
    useCases: ["Port logistics", "Container depot", "Dedicated container movement"],
    rental: "Per trip / dedicated",
    priority: "easy",
    imageKey: "container-trailer-40ft",
    tags: ["40ft-container", "chassis", "port-logistics", "dedicated"],
  },
  {
    id: "side-loader-container",
    number: 14,
    name: { id: "Side Loader Container", en: "Container Side Loader" },
    category: "Container Transportation",
    summary: {
      id: "Trailer dengan sistem angkat hidraulis samping untuk penanganan container di lokasi kerja.",
      en: "A trailer with hydraulic side-lift capability for on-site container handling.",
    },
    useCases: ["Container depot", "Project site", "Self-loading container movement"],
    rental: "Per pekerjaan / harian",
    priority: "standard",
    imageKey: "side-loader-container",
    tags: ["side-loader", "container", "hydraulic-lift", "project-site"],
  },
  {
    id: "reefer-truck",
    number: 15,
    name: { id: "Reefer Truck", en: "Refrigerated Truck" },
    category: "Temperature-Controlled Transport",
    summary: {
      id: "Truk berpendingin untuk kebutuhan kargo dengan rentang temperatur yang ditentukan proyek.",
      en: "A refrigerated truck for cargo requiring a project-defined temperature range.",
    },
    useCases: ["Frozen food", "Pharmaceuticals", "Cold chain", "Temperature-sensitive cargo"],
    rental: "Harian / bulanan / per trip",
    priority: "easy",
    imageKey: "reefer-truck",
    tags: ["reefer", "cold-chain", "refrigerated", "temperature-controlled"],
  },
  {
    id: "car-carrier",
    number: 16,
    name: { id: "Car Carrier", en: "Vehicle Carrier" },
    category: "Automotive Logistics",
    summary: {
      id: "Trailer bertingkat untuk mobilisasi kendaraan penumpang dan kendaraan listrik.",
      en: "A multi-level trailer for transporting passenger vehicles and electric vehicles.",
    },
    useCases: ["Automotive manufacturer", "Dealer distribution", "EV transport", "Fleet relocation"],
    rental: "Per trip",
    priority: "easy",
    imageKey: "car-carrier",
    tags: ["car-carrier", "vehicle-logistics", "automotive", "ev"],
  },
  {
    id: "dump-truck-on-road",
    number: 17,
    name: { id: "Dump Truck On-Road", en: "On-Road Dump Truck" },
    category: "Hauling Vehicle",
    summary: {
      id: "Dump truck jalan raya untuk hauling tanah, pasir, batu, dan material proyek.",
      en: "An on-road dump truck for hauling soil, sand, rock, and project materials.",
    },
    useCases: ["Quarry", "Konstruksi", "Mine support", "Earthwork"],
    rental: "Per ritase / harian / bulanan",
    priority: "top",
    imageKey: "dump-truck-on-road",
    tags: ["dump-truck", "hauling", "earthwork", "quarry"],
  },
  {
    id: "bulk-cement-tanker",
    number: 18,
    name: { id: "Bulk Cement Tanker", en: "Bulk Cement Tanker" },
    category: "Bulk Transportation",
    summary: {
      id: "Tanker powder untuk transportasi semen curah ke fasilitas proyek dan batching plant.",
      en: "A powder tanker for transporting bulk cement to project facilities and batching plants.",
    },
    useCases: ["Batching plant", "Konstruksi", "Bulk material logistics"],
    rental: "Per trip / bulanan",
    priority: "standard",
    imageKey: "bulk-cement-tanker",
    tags: ["cement-tanker", "bulk-powder", "batching-plant", "construction"],
  },
  {
    id: "water-tanker-truck",
    number: 19,
    name: { id: "Water Tanker / Water Truck", en: "Water Tanker / Water Truck" },
    category: "Site Support Vehicle",
    summary: {
      id: "Truk tangki air untuk penyiraman jalan angkut dan pengendalian debu di area proyek.",
      en: "A water tanker for haul-road watering and dust suppression across project sites.",
    },
    useCases: ["Pertambangan", "Konstruksi", "Dust suppression", "Haul-road maintenance"],
    rental: "Harian / bulanan / hour meter",
    priority: "top",
    imageKey: "water-tanker-truck",
    tags: ["water-truck", "tanker", "dust-suppression", "site-support"],
  },
  {
    id: "fuel-tanker-truck",
    number: 20,
    name: { id: "Fuel Tanker / Fuel Truck", en: "Fuel Tanker / Fuel Truck" },
    category: "Site Support Vehicle",
    summary: {
      id: "Kendaraan tangki untuk mendukung distribusi bahan bakar ke equipment sesuai prosedur site.",
      en: "A tanker vehicle supporting fuel distribution to equipment under site procedures.",
    },
    useCases: ["Mine site", "Konstruksi", "Oilfield", "Remote refueling"],
    rental: "Bulanan / full service",
    priority: "standard",
    imageKey: "fuel-tanker-truck",
    tags: ["fuel-truck", "tanker", "refueling", "site-support"],
  },
  {
    id: "vacuum-truck",
    number: 21,
    name: { id: "Vacuum Truck", en: "Vacuum Truck" },
    category: "Industrial Service Vehicle",
    summary: {
      id: "Truk tangki dengan pompa vakum untuk penanganan lumpur, sludge, dan cairan industri.",
      en: "A tank truck with a vacuum pump for handling mud, sludge, and industrial liquids.",
    },
    useCases: ["Oil and gas", "Industrial facility", "Mine workshop", "Liquid waste handling"],
    rental: "Per pekerjaan / harian / bulanan",
    priority: "standard",
    imageKey: "vacuum-truck",
    tags: ["vacuum-truck", "sludge", "industrial-service", "liquid-handling"],
  },
  {
    id: "lowbed-lowboy-trailer",
    number: 22,
    name: { id: "Lowbed / Lowboy Trailer", en: "Lowbed / Lowboy Trailer" },
    category: "Heavy Equipment Transport",
    summary: {
      id: "Trailer berdeck rendah untuk mobilisasi excavator, dozer, loader, crane, dan equipment berat lainnya.",
      en: "A low-deck trailer for mobilizing excavators, dozers, loaders, cranes, and other heavy equipment.",
    },
    useCases: ["Mobilisasi alat berat", "Pertambangan", "Konstruksi", "Project logistics"],
    rental: "Per mobilisasi / per trip",
    priority: "top",
    imageKey: "lowbed-lowboy-trailer",
    tags: ["lowbed", "lowboy", "heavy-equipment", "mobilization"],
  },
  {
    id: "extendable-trailer",
    number: 23,
    name: { id: "Extendable Trailer", en: "Extendable Trailer" },
    category: "Project Transportation",
    summary: {
      id: "Trailer deck yang dapat diperpanjang untuk komponen panjang dan kargo proyek berdimensi khusus.",
      en: "An extendable-deck trailer for long components and dimensionally specialized project cargo.",
    },
    useCases: ["Crane boom", "Pipa panjang", "Struktur baja", "EPC projects"],
    rental: "Berbasis proyek",
    priority: "standard",
    imageKey: "extendable-trailer",
    tags: ["extendable-trailer", "long-cargo", "epc", "oversized"],
  },
  {
    id: "multi-axle-modular-trailer",
    number: 24,
    name: { id: "Multi-Axle / Modular Trailer", en: "Multi-Axle / Modular Trailer" },
    category: "Specialized Project Transport",
    summary: {
      id: "Platform multi-axle untuk sourcing transportasi transformer, vessel, dan mesin super-heavy.",
      en: "A multi-axle platform sourced for transporting transformers, vessels, and super-heavy machinery.",
    },
    useCases: ["EPC", "Refinery", "Power plant", "Heavy-lift logistics"],
    rental: "Berbasis proyek",
    priority: "specialist",
    imageKey: "multi-axle-modular-trailer",
    tags: ["multi-axle", "modular-trailer", "super-heavy", "project-cargo"],
  },
  {
    id: "spmt",
    number: 25,
    name: { id: "SPMT", en: "Self-Propelled Modular Transporter" },
    category: "Specialized Project Transport",
    summary: {
      id: "Platform modular self-propelled untuk kebutuhan pemindahan beban ekstrem berbasis studi proyek.",
      en: "A self-propelled modular platform for extreme-load moves planned through project-specific studies.",
    },
    useCases: ["Refinery", "Shipyard", "Power plant", "Ultra-heavy transport"],
    rental: "Berbasis proyek",
    priority: "specialist",
    imageKey: "spmt",
    tags: ["spmt", "self-propelled", "ultra-heavy", "specialist"],
  },
  {
    id: "lv-4x4-double-cabin",
    number: 100,
    name: { id: "LV 4×4 / Double Cabin", en: "4×4 Light Vehicle / Double Cab" },
    category: "Site Fleet",
    summary: {
      id: "Kendaraan 4×4 untuk mobilitas supervisor, personel, dan operasional di area site.",
      en: "A 4×4 vehicle for supervisor, personnel, and operational mobility across site areas.",
    },
    useCases: ["Mine site", "Project supervision", "Remote operations", "Personnel mobility"],
    rental: "Bulanan / tahunan",
    priority: "top",
    imageKey: "lv-4x4-double-cabin",
    tags: ["4x4", "double-cabin", "light-vehicle", "site-fleet"],
  },
  {
    id: "crew-bus",
    number: 101,
    name: { id: "Crew Bus", en: "Crew Bus" },
    category: "Personnel Transportation",
    summary: {
      id: "Bus kru untuk mendukung perpindahan operator dan personel antara camp dan area kerja.",
      en: "A crew bus supporting operator and personnel movement between camps and work areas.",
    },
    useCases: ["Mine camp", "Project site", "Shift transport", "Personnel shuttle"],
    rental: "Bulanan / tahunan",
    priority: "easy",
    imageKey: "crew-bus",
    tags: ["crew-bus", "personnel", "shuttle", "site-fleet"],
  },
  {
    id: "site-ambulance",
    number: 102,
    name: { id: "Ambulance Site", en: "Site Ambulance" },
    category: "Emergency Support Vehicle",
    summary: {
      id: "Kendaraan ambulans yang dapat disourcing sesuai spesifikasi HSE dan kebutuhan respons darurat site.",
      en: "An ambulance vehicle sourced to site HSE specifications and emergency-response requirements.",
    },
    useCases: ["Mine HSE", "Construction HSE", "Emergency response", "Remote site"],
    rental: "Bulanan / tahunan",
    priority: "easy",
    imageKey: "site-ambulance",
    tags: ["ambulance", "hse", "emergency", "site-fleet"],
  },
  {
    id: "service-pickup",
    number: 103,
    name: { id: "Service Pickup", en: "Service Pickup" },
    category: "Site Support Vehicle",
    summary: {
      id: "Pickup operasional untuk membawa mekanik, peralatan, dan kebutuhan dukungan workshop lapangan.",
      en: "An operational pickup for mechanics, tools, and field-workshop support requirements.",
    },
    useCases: ["Mine workshop", "Field maintenance", "Mechanic transport", "Tool transport"],
    rental: "Bulanan / tahunan",
    priority: "easy",
    imageKey: "service-pickup",
    tags: ["service-pickup", "mechanic", "workshop", "site-support"],
  },
  {
    id: "lowbed-prime-mover-package",
    number: 104,
    name: { id: "Lowbed + Prime Mover", en: "Lowbed + Prime Mover Package" },
    category: "Heavy Equipment Transport",
    summary: {
      id: "Paket prime mover dan lowbed untuk sourcing mobilisasi alat berat antarlokasi proyek.",
      en: "A prime mover and lowbed package sourced for heavy-equipment mobilization between project locations.",
    },
    useCases: ["Mobilisasi alat berat", "Pertambangan", "Konstruksi", "Project relocation"],
    rental: "Per mobilisasi",
    priority: "top",
    imageKey: "lowbed-prime-mover-package",
    tags: ["lowbed", "prime-mover", "equipment-mobilization", "project-logistics"],
  },
] as const;
