export type Catalog77395Item = {
  id: string;
  number: number;
  name: {
    id: string;
    en: string;
  };
  category: string;
  summary: {
    id: string;
    en: string;
  };
  useCases: string[];
  rental: string;
  priority: "top" | "easy" | "standard" | "specialist";
  imageKey: string;
  tags: string[];
};

export const catalog77395: Catalog77395Item[] = [
  {
    id: "excavator-20-30t",
    number: 69,
    name: { id: "Excavator 20–30 Ton", en: "20–30T Excavator" },
    category: "Excavation & Loading",
    summary: {
      id: "Excavator serbaguna untuk pekerjaan drainase, penggalian, dan pendukung produksi di area tambang.",
      en: "A versatile excavator for drainage, excavation, and production-support work at mine sites.",
    },
    useCases: ["Pit drainage", "General excavation", "Mine support"],
    rental: "HM / monthly",
    priority: "standard",
    imageKey: "mining-excavator-20-30t",
    tags: ["excavator", "earthmoving", "drainage", "support"],
  },
  {
    id: "excavator-40-50t",
    number: 70,
    name: { id: "Excavator 40–50 Ton", en: "40–50T Excavator" },
    category: "Excavation & Loading",
    summary: {
      id: "Excavator kelas berat untuk pengupasan overburden dan pemuatan material produksi.",
      en: "A heavy-class excavator for overburden removal and production material loading.",
    },
    useCases: ["Overburden removal", "Truck loading", "Quarry production"],
    rental: "HM / monthly",
    priority: "top",
    imageKey: "mining-excavator-40-50t",
    tags: ["excavator", "overburden", "loading", "production"],
  },
  {
    id: "excavator-70-100t",
    number: 71,
    name: { id: "Excavator 70–100 Ton", en: "70–100T Excavator" },
    category: "Excavation & Loading",
    summary: {
      id: "Excavator berkapasitas besar untuk pemuatan berat dan target produksi bervolume tinggi.",
      en: "A large-capacity excavator for heavy loading and high-volume production targets.",
    },
    useCases: ["Heavy loading", "Bulk excavation", "Large quarry operation"],
    rental: "HM / monthly",
    priority: "specialist",
    imageKey: "mining-excavator-70-100t",
    tags: ["excavator", "heavy-loading", "high-capacity", "production"],
  },
  {
    id: "hydraulic-mining-shovel",
    number: 72,
    name: { id: "Hydraulic Mining Shovel", en: "Hydraulic Mining Shovel" },
    category: "Excavation & Loading",
    summary: {
      id: "Mesin gali dan muat produksi untuk memasangkan bucket berkapasitas besar dengan armada haul truck.",
      en: "A production digging and loading machine designed to pair large buckets with haul-truck fleets.",
    },
    useCases: ["Large haul-truck loading", "Open-pit production", "High-volume excavation"],
    rental: "Long-term contract",
    priority: "specialist",
    imageKey: "hydraulic-mining-shovel",
    tags: ["mining-shovel", "open-pit", "haul-truck", "production"],
  },
  {
    id: "dump-truck-6x4-8x4",
    number: 73,
    name: { id: "Dump Truck 6x4 / 8x4", en: "6x4 / 8x4 Dump Truck" },
    category: "Hauling",
    summary: {
      id: "Dump truck jalan tambang untuk mengangkut tanah, batuan, atau batubara pada rute operasional yang sesuai.",
      en: "A mine-road dump truck for hauling soil, rock, or coal across suitable operating routes.",
    },
    useCases: ["Coal hauling", "Earth hauling", "Quarry transport"],
    rental: "Per trip / monthly",
    priority: "top",
    imageKey: "dump-truck-6x4-8x4",
    tags: ["dump-truck", "hauling", "coal", "quarry"],
  },
  {
    id: "articulated-dump-truck",
    number: 74,
    name: { id: "Articulated Dump Truck (ADT)", en: "Articulated Dump Truck (ADT)" },
    category: "Hauling",
    summary: {
      id: "Hauler berartikulasi untuk memindahkan material di medan lunak, tidak rata, atau berakses terbatas.",
      en: "An articulated hauler for moving material across soft, uneven, or access-constrained terrain.",
    },
    useCases: ["Soft-ground hauling", "Wet-site operation", "Rough-terrain earthmoving"],
    rental: "HM / monthly",
    priority: "specialist",
    imageKey: "articulated-dump-truck",
    tags: ["adt", "hauling", "rough-terrain", "earthmoving"],
  },
  {
    id: "rigid-haul-truck",
    number: 75,
    name: { id: "Rigid Haul Truck", en: "Rigid Haul Truck" },
    category: "Hauling",
    summary: {
      id: "Haul truck off-highway berkapasitas besar untuk siklus angkut material di tambang terbuka.",
      en: "A high-capacity off-highway truck for material haul cycles in large open-pit mines.",
    },
    useCases: ["Open-pit hauling", "Ore transport", "Overburden transport"],
    rental: "HM / long-term contract",
    priority: "specialist",
    imageKey: "rigid-haul-truck",
    tags: ["haul-truck", "off-highway", "open-pit", "high-capacity"],
  },
  {
    id: "wheel-loader",
    number: 76,
    name: { id: "Wheel Loader", en: "Wheel Loader" },
    category: "Excavation & Loading",
    summary: {
      id: "Loader beroda untuk penanganan stockpile, pemuatan truk, dan pemindahan material jarak pendek.",
      en: "A wheeled loader for stockpile handling, truck loading, and short-distance material movement.",
    },
    useCases: ["Stockpile handling", "Truck loading", "Quarry material handling"],
    rental: "HM / monthly",
    priority: "top",
    imageKey: "mining-wheel-loader",
    tags: ["wheel-loader", "stockpile", "loading", "material-handling"],
  },
  {
    id: "large-mining-wheel-loader",
    number: 77,
    name: { id: "Mining Wheel Loader", en: "Mining Wheel Loader" },
    category: "Excavation & Loading",
    summary: {
      id: "Wheel loader kelas tambang untuk pemuatan bervolume tinggi dan pengelolaan stockpile besar.",
      en: "A mining-class wheel loader for high-volume loading and large stockpile management.",
    },
    useCases: ["High-volume loading", "ROM stockpile", "Large truck loading"],
    rental: "HM / monthly",
    priority: "specialist",
    imageKey: "large-mining-wheel-loader",
    tags: ["mining-loader", "high-volume", "stockpile", "production"],
  },
  {
    id: "bulldozer",
    number: 78,
    name: { id: "Bulldozer", en: "Bulldozer" },
    category: "Ground Support",
    summary: {
      id: "Dozer untuk mendorong material, membersihkan area kerja, dan membentuk permukaan site.",
      en: "A dozer for pushing material, cleaning work areas, and shaping site surfaces.",
    },
    useCases: ["Material pushing", "Site cleanup", "Access preparation"],
    rental: "HM / monthly",
    priority: "standard",
    imageKey: "mining-bulldozer",
    tags: ["bulldozer", "site-support", "cleanup", "earthmoving"],
  },
  {
    id: "large-mining-dozer",
    number: 79,
    name: { id: "Large Mining Dozer", en: "Large Mining Dozer" },
    category: "Ground Support",
    summary: {
      id: "Dozer kelas produksi untuk menangani overburden, menjaga area dumping, dan menata stockpile.",
      en: "A production-class dozer for overburden work, dump-area maintenance, and stockpile shaping.",
    },
    useCases: ["Overburden pushing", "Dump-area maintenance", "Stockpile shaping"],
    rental: "HM / monthly",
    priority: "specialist",
    imageKey: "large-mining-dozer",
    tags: ["mining-dozer", "overburden", "dump-area", "production"],
  },
  {
    id: "motor-grader",
    number: 80,
    name: { id: "Motor Grader", en: "Motor Grader" },
    category: "Ground Support",
    summary: {
      id: "Alat perata untuk membangun dan menjaga geometri serta permukaan jalan angkut tambang.",
      en: "A grading machine for building and maintaining mine haul-road geometry and surfaces.",
    },
    useCases: ["Haul-road maintenance", "Road shaping", "Drainage grading"],
    rental: "HM / monthly",
    priority: "top",
    imageKey: "mining-motor-grader",
    tags: ["motor-grader", "haul-road", "road-maintenance", "support"],
  },
  {
    id: "water-truck",
    number: 81,
    name: { id: "Water Truck", en: "Water Truck" },
    category: "Site Support",
    summary: {
      id: "Truk tangki air untuk pengendalian debu dan pembasahan jalan operasional tambang.",
      en: "A water tanker for dust suppression and wetting operational mine roads.",
    },
    useCases: ["Dust suppression", "Haul-road watering", "Site water distribution"],
    rental: "HM / monthly",
    priority: "top",
    imageKey: "mining-water-truck",
    tags: ["water-truck", "dust-control", "haul-road", "hse"],
  },
  {
    id: "fuel-truck",
    number: 82,
    name: { id: "Fuel Truck", en: "Fuel Truck" },
    category: "Site Support",
    summary: {
      id: "Unit pengisian bahan bakar bergerak untuk mendukung alat produksi dan kendaraan operasional di site.",
      en: "A mobile refueling unit supporting production equipment and operational vehicles on site.",
    },
    useCases: ["Field refueling", "Remote equipment support", "Shift fuel distribution"],
    rental: "Monthly",
    priority: "standard",
    imageKey: "mining-fuel-truck",
    tags: ["fuel-truck", "refueling", "site-support", "mobile-service"],
  },
  {
    id: "lube-service-truck",
    number: 83,
    name: { id: "Lube / Service Truck", en: "Lube / Service Truck" },
    category: "Site Support",
    summary: {
      id: "Workshop bergerak untuk membawa pelumas, grease, tools, dan perlengkapan servis lapangan.",
      en: "A mobile workshop carrying lubricants, grease, tools, and field-service equipment.",
    },
    useCases: ["Field lubrication", "Preventive service", "Mobile workshop support"],
    rental: "Monthly",
    priority: "specialist",
    imageKey: "lube-service-truck",
    tags: ["lube-truck", "service-truck", "maintenance", "workshop"],
  },
  {
    id: "tyre-handler",
    number: 84,
    name: { id: "Tyre Handler", en: "Tyre Handler" },
    category: "Site Support",
    summary: {
      id: "Attachment atau unit khusus untuk membantu pelepasan, pemindahan, dan pemasangan ban alat tambang berukuran besar.",
      en: "A specialized attachment or machine for removing, moving, and installing large mining-equipment tyres.",
    },
    useCases: ["Haul-truck tyre change", "Workshop tyre handling", "Large tyre positioning"],
    rental: "Monthly / project-based",
    priority: "specialist",
    imageKey: "mining-tyre-handler",
    tags: ["tyre-handler", "haul-truck", "workshop", "specialized"],
  },
  {
    id: "blasthole-drill",
    number: 85,
    name: { id: "Blasthole Drill", en: "Blasthole Drill" },
    category: "Drilling & Breaking",
    summary: {
      id: "Rig pengeboran produksi untuk membuat pola lubang peledakan sesuai rancangan drill-and-blast.",
      en: "A production drill rig for creating blast-hole patterns to a drill-and-blast design.",
    },
    useCases: ["Production drilling", "Blast-hole pattern drilling", "Bench preparation"],
    rental: "HM / monthly",
    priority: "specialist",
    imageKey: "blasthole-drill",
    tags: ["drill-rig", "blasting", "open-pit", "production"],
  },
  {
    id: "rock-drill",
    number: 86,
    name: { id: "Rock Drill", en: "Rock Drill" },
    category: "Drilling & Breaking",
    summary: {
      id: "Rig bor batu untuk pekerjaan quarry, bench drilling, dan persiapan peledakan sesuai kebutuhan teknis.",
      en: "A rock drill rig for quarry work, bench drilling, and blast preparation to technical requirements.",
    },
    useCases: ["Quarry drilling", "Bench drilling", "Rock-face preparation"],
    rental: "HM",
    priority: "specialist",
    imageKey: "rock-drill-rig",
    tags: ["rock-drill", "quarry", "bench-drilling", "drill-blast"],
  },
  {
    id: "rock-breaker",
    number: 87,
    name: { id: "Rock Breaker", en: "Rock Breaker" },
    category: "Drilling & Breaking",
    summary: {
      id: "Hydraulic breaker untuk memecah batuan berukuran berlebih agar dapat ditangani atau diproses lebih lanjut.",
      en: "A hydraulic breaker for reducing oversized rock before further handling or processing.",
    },
    useCases: ["Oversize rock breaking", "Quarry face work", "Crusher feed preparation"],
    rental: "HM",
    priority: "standard",
    imageKey: "excavator-rock-breaker",
    tags: ["rock-breaker", "hydraulic-breaker", "oversize", "quarry"],
  },
  {
    id: "mobile-crusher",
    number: 88,
    name: { id: "Mobile Crusher", en: "Mobile Crusher" },
    category: "Crushing & Processing",
    summary: {
      id: "Unit crushing bergerak yang dapat ditempatkan dekat sumber material untuk mengurangi kebutuhan pemindahan awal.",
      en: "A mobile crushing unit deployable near the material source to reduce initial material movement.",
    },
    useCases: ["On-site crushing", "Quarry processing", "Recycled aggregate production"],
    rental: "Monthly / project-based",
    priority: "specialist",
    imageKey: "mobile-crusher",
    tags: ["crusher", "mobile-plant", "aggregate", "processing"],
  },
  {
    id: "jaw-crusher",
    number: 89,
    name: { id: "Jaw Crusher", en: "Jaw Crusher" },
    category: "Crushing & Processing",
    summary: {
      id: "Primary crusher untuk menerima batuan awal dan mereduksinya ke ukuran umpan tahap berikutnya.",
      en: "A primary crusher that receives run-of-mine rock and reduces it for the next processing stage.",
    },
    useCases: ["Primary crushing", "ROM material reduction", "Quarry processing"],
    rental: "Monthly / project-based",
    priority: "specialist",
    imageKey: "jaw-crusher",
    tags: ["jaw-crusher", "primary-crushing", "rom", "quarry"],
  },
  {
    id: "cone-crusher",
    number: 90,
    name: { id: "Cone Crusher", en: "Cone Crusher" },
    category: "Crushing & Processing",
    summary: {
      id: "Secondary crusher untuk memperkecil dan membentuk material setelah proses primary crushing.",
      en: "A secondary crusher for further size reduction and shaping after primary crushing.",
    },
    useCases: ["Secondary crushing", "Aggregate shaping", "Mineral size reduction"],
    rental: "Monthly / project-based",
    priority: "specialist",
    imageKey: "cone-crusher",
    tags: ["cone-crusher", "secondary-crushing", "aggregate", "processing"],
  },
  {
    id: "mobile-screening-plant",
    number: 91,
    name: { id: "Mobile Screening Plant", en: "Mobile Screening Plant" },
    category: "Crushing & Processing",
    summary: {
      id: "Screening plant bergerak untuk memisahkan material berdasarkan fraksi ukuran di lokasi operasi.",
      en: "A mobile screening plant for separating material into size fractions at the operating site.",
    },
    useCases: ["Aggregate sizing", "Coal screening", "Crusher circuit support"],
    rental: "Monthly",
    priority: "specialist",
    imageKey: "mobile-screening-plant",
    tags: ["screening-plant", "sizing", "aggregate", "mobile-plant"],
  },
  {
    id: "conveyor-system",
    number: 92,
    name: { id: "Conveyor System", en: "Conveyor System" },
    category: "Stockpile & Conveying",
    summary: {
      id: "Sistem konveyor modular atau tetap untuk memindahkan batubara, mineral, dan agregat secara kontinu.",
      en: "A modular or fixed conveyor system for the continuous transfer of coal, minerals, and aggregates.",
    },
    useCases: ["Coal transfer", "Plant feed", "Stockpile transfer"],
    rental: "Project-based",
    priority: "specialist",
    imageKey: "mining-conveyor-system",
    tags: ["conveyor", "bulk-material", "coal", "processing"],
  },
  {
    id: "stacker",
    number: 93,
    name: { id: "Stacker", en: "Stacker" },
    category: "Stockpile & Conveying",
    summary: {
      id: "Peralatan penumpuk material curah untuk membentuk stockpile secara terkontrol dan berkelanjutan.",
      en: "Bulk-material stacking equipment for forming controlled, continuous stockpiles.",
    },
    useCases: ["Coal stockpiling", "Ore stockpiling", "Port stockyard operation"],
    rental: "Project-based",
    priority: "specialist",
    imageKey: "mining-stacker",
    tags: ["stacker", "stockpile", "coal-handling", "bulk-material"],
  },
  {
    id: "reclaimer",
    number: 94,
    name: { id: "Reclaimer", en: "Reclaimer" },
    category: "Stockpile & Conveying",
    summary: {
      id: "Peralatan pengambil kembali material curah dari stockpile untuk diteruskan ke conveyor atau proses berikutnya.",
      en: "Equipment that recovers bulk material from stockpiles for onward conveying or processing.",
    },
    useCases: ["Stockpile reclaiming", "Coal terminal operation", "Plant-feed recovery"],
    rental: "Project-based",
    priority: "specialist",
    imageKey: "mining-reclaimer",
    tags: ["reclaimer", "stockpile", "terminal", "bulk-material"],
  },
  {
    id: "dewatering-pump",
    number: 95,
    name: { id: "Dewatering Pump", en: "Dewatering Pump" },
    category: "Dewatering",
    summary: {
      id: "Pompa untuk mengendalikan akumulasi air dan menjaga area pit atau kerja tetap operasional.",
      en: "A pump for controlling accumulated water and helping keep pit or work areas operational.",
    },
    useCases: ["Pit dewatering", "Sump drainage", "Quarry water control"],
    rental: "Monthly",
    priority: "easy",
    imageKey: "dewatering-pump",
    tags: ["pump", "dewatering", "pit", "drainage"],
  },
  {
    id: "high-capacity-pump",
    number: 96,
    name: { id: "High-Capacity Pump", en: "High-Capacity Pump" },
    category: "Dewatering",
    summary: {
      id: "Sistem pompa berdebit besar untuk drainase berat, bypass, dan respons genangan di area proyek.",
      en: "A high-flow pumping system for heavy drainage, bypass duties, and site flood response.",
    },
    useCases: ["Flood control", "High-flow drainage", "Emergency water bypass"],
    rental: "Monthly / project-based",
    priority: "easy",
    imageKey: "high-capacity-pump",
    tags: ["pump", "high-flow", "flood-control", "dewatering"],
  },
  {
    id: "lighting-tower",
    number: 97,
    name: { id: "Lighting Tower", en: "Lighting Tower" },
    category: "Power & Utilities",
    summary: {
      id: "Menara lampu portabel untuk penerangan area kerja, jalan, workshop, dan aktivitas shift malam.",
      en: "A portable light tower for illuminating work zones, roads, workshops, and night-shift activities.",
    },
    useCases: ["Night-shift lighting", "Workshop lighting", "Remote work-area lighting"],
    rental: "Monthly",
    priority: "easy",
    imageKey: "mining-lighting-tower",
    tags: ["lighting-tower", "night-shift", "site-utility", "portable"],
  },
  {
    id: "generator-genset",
    number: 98,
    name: { id: "Generator / Genset", en: "Generator Set" },
    category: "Power & Utilities",
    summary: {
      id: "Sumber listrik mandiri untuk camp, workshop, pompa, kantor site, atau peralatan pendukung.",
      en: "An independent power source for camps, workshops, pumps, site offices, or support equipment.",
    },
    useCases: ["Temporary site power", "Workshop power", "Backup power"],
    rental: "Monthly",
    priority: "easy",
    imageKey: "industrial-generator-set",
    tags: ["generator", "genset", "power", "site-utility"],
  },
  {
    id: "air-compressor",
    number: 99,
    name: { id: "Air Compressor", en: "Air Compressor" },
    category: "Power & Utilities",
    summary: {
      id: "Sumber udara bertekanan untuk workshop, pembersihan, dan peralatan pneumatik di lapangan.",
      en: "A compressed-air source for workshops, cleaning, and pneumatic field equipment.",
    },
    useCases: ["Pneumatic tools", "Workshop support", "Drilling support"],
    rental: "Monthly",
    priority: "easy",
    imageKey: "portable-air-compressor",
    tags: ["air-compressor", "pneumatic", "workshop", "site-utility"],
  },
  {
    id: "lv-4x4-double-cabin",
    number: 100,
    name: { id: "LV 4x4 / Double Cabin", en: "4x4 Light Vehicle / Double Cab" },
    category: "Personnel & Service Mobility",
    summary: {
      id: "Kendaraan ringan 4x4 untuk mobilitas supervisor, teknisi, dan personel operasional di area site.",
      en: "A 4x4 light vehicle for supervisors, technicians, and operational personnel at mine sites.",
    },
    useCases: ["Supervisor mobility", "Site inspection", "Field personnel transport"],
    rental: "Monthly / yearly",
    priority: "top",
    imageKey: "mining-lv-double-cabin-4x4",
    tags: ["light-vehicle", "double-cabin", "4x4", "site-mobility"],
  },
  {
    id: "crew-bus",
    number: 101,
    name: { id: "Crew Bus", en: "Crew Bus" },
    category: "Personnel & Service Mobility",
    summary: {
      id: "Bus operasional untuk perpindahan operator dan kru antara camp, muster point, dan area kerja.",
      en: "An operational bus for moving operators and crews between camps, muster points, and work areas.",
    },
    useCases: ["Shift transport", "Camp-to-site transfer", "Crew mobilization"],
    rental: "Monthly / yearly",
    priority: "easy",
    imageKey: "mining-crew-bus",
    tags: ["crew-bus", "personnel", "shift-transport", "site-mobility"],
  },
  {
    id: "site-ambulance",
    number: 102,
    name: { id: "Ambulans Site", en: "Site Ambulance" },
    category: "Personnel & Service Mobility",
    summary: {
      id: "Kendaraan respons medis yang dikonfigurasi untuk mendukung kesiapsiagaan darurat di area operasi.",
      en: "A medical-response vehicle configured to support emergency readiness at operational sites.",
    },
    useCases: ["Emergency response", "Mine HSE support", "Remote-site medical transport"],
    rental: "Monthly / yearly",
    priority: "easy",
    imageKey: "mining-site-ambulance",
    tags: ["ambulance", "hse", "emergency", "site-support"],
  },
  {
    id: "service-pickup",
    number: 103,
    name: { id: "Service Pickup", en: "Service Pickup" },
    category: "Personnel & Service Mobility",
    summary: {
      id: "Pickup kerja untuk membawa mekanik, tools, komponen kecil, dan perlengkapan perawatan menuju unit.",
      en: "A work pickup for carrying mechanics, tools, small parts, and maintenance equipment to assets.",
    },
    useCases: ["Mechanic mobility", "Tool transport", "Field maintenance support"],
    rental: "Monthly / yearly",
    priority: "easy",
    imageKey: "mining-service-pickup",
    tags: ["service-pickup", "mechanic", "maintenance", "tools"],
  },
  {
    id: "lowbed-prime-mover",
    number: 104,
    name: { id: "Lowbed + Prime Mover", en: "Lowbed Trailer + Prime Mover" },
    category: "Equipment Mobilization",
    summary: {
      id: "Kombinasi tractor head dan lowbed untuk mobilisasi alat berat sesuai dimensi, bobot, rute, dan perizinan angkutan.",
      en: "A tractor-and-lowbed combination for mobilizing heavy equipment subject to dimensions, weight, route, and transport permits.",
    },
    useCases: ["Excavator mobilization", "Dozer transport", "Inter-site equipment transfer"],
    rental: "Per move / per trip",
    priority: "top",
    imageKey: "lowbed-prime-mover-heavy-equipment",
    tags: ["lowbed", "prime-mover", "mobilization", "heavy-haul"],
  },
];
